- name: Install deb packages
  apt:
    state: latest
    name:
      - curl
      - ca-certificates
      - git
      - python3
      - python3-pip
      - python3-venv
      - python3-pexpect                    
      - kubernetes-client
      - gnupg
      - lsb-release          
  become: yes